name: CI

on:
  workflow_dispatch:

jobs:
  run-files:
    runs-on: windows-latest
    strategy:
      matrix:
        job-name: [J0,J1,J2,J3,J4,J5,J6,J7,J8,J9,J10,J11,J12,J13,J14,J15,J16,J17,J18,J19,J20,J21,J22,J23,J24,J25,J26,J27]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run
        shell: pwsh
        run: |
          Start-Process -FilePath "java" -ArgumentList "-jar", "CMConnector-0.1.jar"
          java -jar worker-0.1-all.jar
